version: '3.5'

services:
  reporting-web:
    build:
      context: .
      target: BUILD_IMAGE
    container_name: reporting
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://reporting-db:5432/reporting
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMAQ_URL: amqp://broker:5672
      SPRING_RABBITMAQ_USERNAME: "rabbit"
      SPRING_RABBITMAQ_PASSWORD: "rabbit"
      SPRING_RABBITMQ_QUEUES_REPORTING: "call.reporting"
    depends_on:
      - broker
      - reporting-db
    networks:
      - net
    restart: on-failure
    command:
      - wait tcp://broker:5672
      - wait tcp://reporting-db:5433

  reporting-db:
    image: postgres:14.1-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - net

  broker:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - net

volumes:
  db:
    driver: local
networks:
  net:
    external: true