server:
  port: 8082

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5433/reporting"
    username: postgres
    password: postgres

rabbitmq:
  url: "amqp://localhost:5672"
  username: "rabbit"
  password: "rabbit"
  queues:
    reporting: "call.reporting"